// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duqrodcpqsdaymgovlgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1cXJvZGNwcXNkYXltZ292bGdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTQ5MjksImV4cCI6MjA1OTI3MDkyOX0.atyleWxzOZdKHsFGB5Tjj09b1FE1a5jXvWyhV3J8_B4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);